import type { NewsCategory } from './enums';
import type { News } from './news';

export interface GenerateNewsDto {
  category?: NewsCategory;
  topic?: string;
  count?: number;
}

export interface AutoGenerateDto {
  countPerCategory?: number;
}

/** Response from POST /ai/auto-generate (React/Vue admin) */
export interface AutoGenerateResponse {
  totalGenerated: number;
  byCategory: Record<string, number>;
}

export interface AiGenerateResponse {
  news: News[];
  count: number;
  category: NewsCategory;
}

export interface AiAutoGenerateResponse {
  news: News[];
  totalCount: number;
  categories: NewsCategory[];
}

export interface AiStatusResponse {
  available: boolean;
  model: string;
  quota: number;
}

export interface CronScheduleResponse {
  cron: string;
}
