export enum NewsCategory {
  POLITICS = 'politics',
  ECONOMY = 'economy',
  TECHNOLOGY = 'technology',
  SCIENCE = 'science',
  SPORTS = 'sports',
  ENTERTAINMENT = 'entertainment',
  HEALTH = 'health',
  WORLD = 'world',
  OTHER = 'other',
}

export enum NewsStatus {
  DRAFT = 'draft',
  PENDING = 'pending',
  PUBLISHED = 'published',
  REJECTED = 'rejected',
  ARCHIVED = 'archived',
}

export enum UserRole {
  USER = 'user',
  MODERATOR = 'moderator',
  ADMIN = 'admin',
  SUPER_ADMIN = 'super_admin',
}

export interface UserPreferences {
  categories: string[];
  tags: string[];
  language: string;
  notificationsEnabled: boolean;
  emailNotifications: boolean;
  theme: 'light' | 'dark';
}

export interface UserResponse {
  id: string;
  email: string;
  username: string;
  firstName?: string;
  lastName?: string;
  avatar?: string;
  role: UserRole;
  preferences: UserPreferences;
  isActive: boolean;
  lastLoginAt?: string;
  createdAt: string;
  updatedAt: string;
}

export interface TokenResponse {
  accessToken: string;
  refreshToken: string;
  expiresIn: number;
}

export interface AuthResponse extends TokenResponse {
  user: UserResponse;
}

export interface JwtPayload {
  sub: string;
  email: string;
  role: string;
  iat?: number;
  exp?: number;
}

export interface ProfileUpdateData {
  firstName?: string;
  lastName?: string;
  avatar?: string;
}

export interface NewsFilter {
  page?: number;
  limit?: number;
  category?: NewsCategory;
  status?: NewsStatus;
  search?: string;
  tags?: string[];
  fromDate?: string;
  toDate?: string;
  sortBy?: 'publishedAt' | 'views' | 'likes';
  sortOrder?: 'ASC' | 'DESC';
  isAiGenerated?: boolean;
  authorId?: string;
}

export interface ModerationBody {
  status: NewsStatus;
  comment?: string;
}

export interface NewsItem {
  id: string;
  title: string;
  content: string;
  summary?: string;
  imageUrl?: string;
  source?: string;
  sourceUrl?: string;
  category: NewsCategory;
  tags: string[];
  status: NewsStatus;
  views: number;
  likes: number;
  isAiGenerated: boolean;
  authorId?: string;
  author?: UserResponse;
  publishedAt?: string;
  createdAt: string;
  updatedAt: string;
  isLiked?: boolean;
  isFavorite?: boolean;
}

export interface RegisterDto {
  email: string;
  username: string;
  password: string;
  firstName?: string;
  lastName?: string;
}

export interface LoginDto {
  email: string;
  password: string;
  rememberMe?: boolean;
}

export interface CreateNewsDto {
  title: string;
  content: string;
  summary?: string;
  imageUrl?: string;
  source?: string;
  sourceUrl?: string;
  category: NewsCategory;
  tags?: string[];
  isAiGenerated?: boolean;
}

export interface UpdateUserDto {
  email?: string;
  username?: string;
  firstName?: string;
  lastName?: string;
  role?: UserRole;
  isActive?: boolean;
  preferences?: Partial<UserPreferences>;
}

export interface GenerateNewsDto {
  category?: NewsCategory;
  topic?: string;
  count?: number;
}

export interface AutoGenerateDto {
  countPerCategory?: number;
}

export interface StatsResponse {
  totalNews: number;
  publishedNews: number;
  totalUsers: number;
  totalLikes: number;
  newsByCategory: Record<string, number>;
}

export interface NewsResponse {
  data: NewsItem[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}
