import type { AutoGenerateDto, GenerateNewsDto } from '@/app/types';
import { useApi } from '@/app/services/api';

export function useAiService() {
  const { apiFetch } = useApi();

  async function generateNews(data: GenerateNewsDto): Promise<any> {
    return apiFetch('/ai/generate', {
      method: 'POST',
      body: JSON.stringify(data),
    });
  }

  async function autoGenerate(data: AutoGenerateDto): Promise<any> {
    return apiFetch('/ai/auto-generate', {
      method: 'POST',
      body: JSON.stringify(data),
    });
  }

  async function checkStatus(): Promise<any> {
    return apiFetch('/ai/status');
  }

  return {
    generateNews,
    autoGenerate,
    checkStatus,
  };
}
