import type {
  AutoGenerateDto,
  GenerateNewsDto,
  AiGenerateResponse,
  AiAutoGenerateResponse,
  AiStatusResponse,
} from '~/types';

export function useAiService() {
  const { apiFetch } = useApi();

  async function generateNews(data: GenerateNewsDto): Promise<AiGenerateResponse> {
    return apiFetch<AiGenerateResponse>('/ai/generate', {
      method: 'POST',
      body: JSON.stringify(data),
    });
  }

  async function autoGenerate(data: AutoGenerateDto): Promise<AiAutoGenerateResponse> {
    return apiFetch<AiAutoGenerateResponse>('/ai/auto-generate', {
      method: 'POST',
      body: JSON.stringify(data),
    });
  }

  async function checkStatus(): Promise<AiStatusResponse> {
    return apiFetch<AiStatusResponse>('/ai/status');
  }

  return {
    generateNews,
    autoGenerate,
    checkStatus,
  };
}
