import { ApiPropertyOptional } from '@nestjs/swagger';
import { IsOptional, IsNumber, Min, Max } from 'class-validator';

export class AutoGenerateDto {
  @ApiPropertyOptional({
    description: 'Количество новостей на каждую категорию',
    example: 1,
    default: 1,
    minimum: 1,
    maximum: 10,
  })
  @IsOptional()
  @IsNumber()
  @Min(1)
  @Max(10)
  countPerCategory?: number = 1;
}